Add following proctoring exam pages: user verification, software download, ready to start instruction
raccoongang/frontend-lib-special-exams pull request #17
Opened 2021-05-25 06:16 UTC by ViktorRusakov

Added user verification, software download, ready to start instructions pages for proctoring exam flow.

[OeX_Proctoring-149](https://youtrack.raccoongang.com/issue/OeX_Proctoring-149)
[OeX_Proctoring-154](https://youtrack.raccoongang.com/issue/OeX_Proctoring-154)
[OeX_Proctoring-208](https://youtrack.raccoongang.com/issue/OeX_Proctoring-208)

2021-05-25 12:05 UTC, idegtiarov requested changes
Currently, tests are failed, could you please fix them so we can go further in the review process.

2021-05-25 12:45 UTC, ihor-romaniuk approved these changes

2021-05-26 11:50 UTC, idegtiarov approved these changes
Looks good so far.

2021-05-26 11:52 UTC, UvgenGen approved these changes

2021-05-27 13:33 UTC, merged