[BD-26] Reduce number of API calls
raccoongang/frontend-lib-special-exams pull request #46
Opened 2021-06-14 07:00 UTC by ViktorRusakov

Reduce number of calls made to exam attempt API

[YouTrack](https://youtrack.raccoongang.com/issue/OeX_Proctoring-238)

2021-06-14 08:34 UTC, idegtiarov requested changes
Nit, other LGTM

2021-06-14 08:34 UTC, idegtiarov commented on src/data/__snapshots__/redux.test.jsx.snap
> +    "initialDataLoaded": true,
`initial` is not clear enough could we rename it to a more accurate name e.g.:  `isLoadingAttemptData`

2021-06-14 13:55 UTC, UvgenGen commented on src/data/slice.js
> +        state.initialDataLoaded = true;
When we switch initialDataLoaded to false?

2021-06-15 08:38 UTC, UvgenGen approved these changes

2021-06-15 09:21 UTC, idegtiarov approved these changes

2021-06-15 09:21 UTC, merged