feat: [OeX_Proctoring-178] (Proctored exam epic) add mock api for fetching proctoring settings
raccoongang/frontend-lib-special-exams pull request #9
Opened 2021-05-11 09:09 UTC by ihor-romaniuk

**Description:** add mock API for fetching proctoring settings and proctoring entrance instruction

**Youtrack:** https://youtrack.raccoongang.com/issue/OeX_Proctoring-178

2021-05-11 20:45 UTC, TamoshaytisV requested changes

2021-05-11 20:45 UTC, TamoshaytisV commented on src/exam/Sequence.jsx
> +  loadProctoringSetting: getProctoringSettings,
```suggestion
  loadProctoringSettings: getProctoringSettings,
```

2021-05-11 20:45 UTC, TamoshaytisV commented on src/exam/Sequence.jsx
> +  loadProctoringSetting: PropTypes.func.isRequired,
```suggestion
  loadProctoringSettings: PropTypes.func.isRequired,
```

2021-05-11 20:45 UTC, TamoshaytisV commented on src/exam/Sequence.jsx
> +      await loadProctoringSetting();
```suggestion
      await loadProctoringSettings();
```

2021-05-11 20:45 UTC, TamoshaytisV commented on src/exam/Sequence.jsx
> +    sequence, courseId, loadExamData, loadProctoringSetting, ...examProps
```suggestion
    sequence, courseId, loadExamData, loadProctoringSettings, ...examProps
```

2021-05-11 20:45 UTC, TamoshaytisV commented on src/exam/Sequence.jsx
> +      await loadProctoringSetting();
Why do we await in this line but don't in the next one? Can we call both asyncroniously?

2021-05-11 20:45 UTC, TamoshaytisV commented on src/instructions/index.jsx
> +  if (isProctored) {
Can we use the common logic like this?
```js
switch (true) {
  case !examHasAttempt:
    return isProctored
      ? <EntranceProctoredExamInstructions />
      : <StartExamInstructions />;
  case attempt.attempt_status === ExamStatus.CREATED:
    return <VerificationProctoredExamInstructions />;
  case attempt.attempt_status === ExamStatus.READY_TO_SUBMIT:
    return <SubmitExamInstructions />;
  case attempt.attempt_status === ExamStatus.SUBMITTED:
    return <SubmittedExamInstructions />;
  default:
    return children;
```

2021-05-11 20:45 UTC, TamoshaytisV commented on src/instructions/proctored_exam/EntranceProctoredExamInstructions.jsx
> +const mapExamStateToProps = (state) => {
Do we need `mapExamStateToProps` at all? I see you are not using this values in props

2021-05-11 20:45 UTC, TamoshaytisV commented on src/instructions/proctored_exam/VerificationProctoredExamInstructions.jsx
> +            defaultMessage="Can I request additional time to complete my exam?"
Is this message really present on verification instructions page?

2021-05-11 20:45 UTC, TamoshaytisV commented on src/instructions/proctored_exam/VerificationProctoredExamInstructions.jsx
> +export default withExamStore(
Why do we need to wrap the component with `withExamStore`? You do not use any store state values

2021-05-12 05:44 UTC, ihor-romaniuk commented on src/exam/Sequence.jsx
> +      await loadProctoringSetting();
If we don't use async/await construction in the first render the component shows "timed exam instruction" and after that switch on the correct "proctoring instruction". Maybe you have a more correct way to solve it.

2021-05-12 05:44 UTC, ihor-romaniuk commented on src/exam/Sequence.jsx
> +    sequence, courseId, loadExamData, loadProctoringSetting, ...examProps
changed

2021-05-12 05:44 UTC, ihor-romaniuk commented on src/exam/Sequence.jsx
> +      await loadProctoringSetting();
changed

2021-05-12 05:44 UTC, ihor-romaniuk commented on src/exam/Sequence.jsx
> +  loadProctoringSetting: PropTypes.func.isRequired,
changed

2021-05-12 05:44 UTC, ihor-romaniuk commented on src/exam/Sequence.jsx
> +  loadProctoringSetting: getProctoringSettings,
changed

2021-05-12 05:46 UTC, ihor-romaniuk commented on src/instructions/index.jsx
> +  if (isProctored) {
completely agree with you!

2021-05-12 05:47 UTC, ihor-romaniuk commented on src/instructions/proctored_exam/EntranceProctoredExamInstructions.jsx
> +const mapExamStateToProps = (state) => {
Removed. Thanks

2021-05-12 05:50 UTC, ihor-romaniuk commented on src/instructions/proctored_exam/VerificationProctoredExamInstructions.jsx
> +            defaultMessage="Can I request additional time to complete my exam?"
I got that instruction text without no connected proctoring providers. Maybe it's a blank instruction and we will see another one with an enabled proctoring provider.

2021-05-12 05:50 UTC, ihor-romaniuk commented on src/instructions/proctored_exam/VerificationProctoredExamInstructions.jsx
> +export default withExamStore(
fixed

2021-05-12 07:33 UTC, ihor-romaniuk commented on src/exam/Sequence.jsx
> +      await loadProctoringSetting();
changed structure

2021-05-13 10:13 UTC, TamoshaytisV commented
Introduce ENV variable to enable/disable proctored exam support. Goal: disable proctored exams on production unless feature is ready; enable development process locally

2021-05-18 13:08 UTC, UvgenGen commented on src/exam/Sequence.jsx
> +const SequenceExamWrapper = ({ children, ...props }) => {
after refactoring, "SequenceExamWrapper" from "src/exc/Sequence.jsx" is not used. moved to "src/index.jsx"

2021-05-21 12:30 UTC, ihor-romaniuk commented
This PR was reopened -> https://github.com/raccoongang/frontend-lib-special-exams/pull/14

2021-05-21 12:30 UTC, closed without merging